# Generated by Django 4.2.11 on 2024-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=1)),
                ('slug', models.SlugField(blank=1, max_length=200, null=1, unique=1)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
